apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html;
      }

      # Proxy API calls to backend
      location /api/ {
        proxy_pass http://careers-backend-service:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
